---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Duration of Trip/Duration of Trip.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/249361/articles/335431/master/file/figures/Duration%20of%20Trip/Duration%20of%20Trip.png"
    folder_url: "/users/249361/articles/335431/master/folder/figures/Duration of Trip"
